### ISSUE TITLE
NPM Build doesn't create CSS file

### ISSUE THREAD

**Issue by RizaHKhan** [CdTgr/vue3-q-tel-input#12]
The `dist` file does not include the CSS file. That import is now failing on my project which is using this component.

```
import '~vue3-q-tel-input/dist/vue3-q-tel-input.esm.css'
```

**Comment by CdTgr** [comment]
Should be resolved in version [1.0.23](https://www.npmjs.com/package/vue3-q-tel-input/v/1.0.23)
