### ISSUE TITLE
q-tel-number could be clickable

### ISSUE THREAD

**Issue by jojooyoo** [CdTgr/vue3-q-tel-input#17]
![320901533_532313538950421_5902974111869235632_n](https://user-images.githubusercontent.com/115844041/209441093-f6012c2f-62ed-4b84-bc56-c603f4ba4f77.jpg)

it would be a great update if the country options were clickable for the user!

**Comment by CdTgr** [comment]
@jojooyoo Could you please be more descriptive? Is is something that's not working?

**Comment by CdTgr** [comment]
Closing as there are no detailed information regarding the bug.
