### ISSUE TITLE
readonly, disabled and dense props are not properly passed to country select control

### ISSUE THREAD

**Issue by FragsterAt** [CdTgr/vue3-q-tel-input#19]

**Comment by CdTgr** [comment]
@FragsterAt A little bit of description could be useful for future reference.

**Comment by FragsterAt** [comment]
props readonly, dense and disable doen not passed to country selection q-select. Before pr #20, they must be specified in dropdown-options, that is a little confusing, especially for readonly, with this pr they inherited from component props/
