### ISSUE TITLE
How to get selected country ?

### ISSUE THREAD

**Issue by Kenddriz** [CdTgr/vue3-q-tel-input#27]
Hi there ? Is there a way to get selected country ?

**Comment by CdTgr** [comment]
there isn't any, but I can add that.

**Comment by CdTgr** [comment]
@Kenddriz The selected country is now available in the `country` emitter. Please use the latest version [v.1.1.4](https://www.npmjs.com/package/vue3-q-tel-input/v/1.1.4)
