### ISSUE TITLE
Select & search country

### ISSUE THREAD

**Issue by Kenddriz** [CdTgr/vue3-q-tel-input#29]
Hi. 
1 - I **can't get @country event work**. The other events work.

2 - **When I search with wrong text, example kxgqhgg, popup gets closed, and I can't reopen it unless I reload my page**.

**Comment by CdTgr** [comment]
@Kenddriz  Did you really try it on the latest version? Also, please provide a minimum reproducible code. maybe a code pen.

**Comment by Kenddriz** [comment]
![code](https://user-images.githubusercontent.com/49997899/224786286-a56fd30f-f2fa-46e1-aa20-15e9ffac547f.PNG)
![vue3tel](https://user-images.githubusercontent.com/49997899/224786317-195a5800-37da-4afb-9316-c01bd61be99e.PNG)
package.json and code

**Comment by Kenddriz** [comment]
Event @country works.
But when I search with wrong text, example kxgqhgg, popup gets closed, and I can't reopen it unless I reload my page.

Thank you!

**Comment by CdTgr** [comment]
@Kenddriz This issue should be resolved in the latest version [v1.1.5](https://www.npmjs.com/package/vue3-q-tel-input/v/1.1.5)
