### ISSUE TITLE
Css breaking?

### ISSUE THREAD

**Issue by Iscrimou** [CdTgr/vue3-q-tel-input#31]
I'm importing css normally on my component, but the flags are this way, what it can be?

![Screenshot 2023-04-27 at 15-33-55 SocialHub Contatos](https://user-images.githubusercontent.com/62183829/234959407-e441810f-265c-497f-9ac4-6117c1c8d0e8.png)

My component:

```
<script>
import Vue3QTelInput from 'vue3-q-tel-input'
import 'vue3-q-tel-input/dist/vue3-q-tel-input.esm.css'
```

**Comment by CdTgr** [comment]
Are you sure that you are not overriding any styles?

**Comment by Iscrimou** [comment]
> Are you sure that you are not overriding any styles?

that component has no styles, just a min-width on q-card, nothing more

**Comment by CdTgr** [comment]
@Iscrimou I don't see any issues with the styles, could you please provide a minimum reproducible code?

**Comment by Iscrimou** [comment]
The problem looks run in dev mode, after I build my application these break disappear
