### ISSUE TITLE
now readonly, disable and dense props are affecting only the country selector, not the input

### ISSUE THREAD

**Issue by CdTgr** [CdTgr/vue3-q-tel-input#32]
now readonly, disable and dense props are affecting only the country selector, not the input

![Screenshot 2023-05-04 at 13-38-11 SocialHub Contatos](https://user-images.githubusercontent.com/62183829/236269580-6048bf26-8315-4997-b750-8561322c6f07.png)
![Captura de tela de 2023-05-04 13-38-23](https://user-images.githubusercontent.com/62183829/236269619-11880c36-5b63-4f72-83e4-2a2c131e8961.png)

_Originally posted by @Iscrimou in https://github.com/CdTgr/vue3-q-tel-input/pull/20#issuecomment-1535061391_

**Comment by FragsterAt** [comment]
look at pr #33 - v-bind newer worked as expected (
