### ISSUE TITLE
Country Switching on entering phone number

### ISSUE THREAD

**Issue by keithchilek** [CdTgr/vue3-q-tel-input#34]
I am assuming the issue is related to countries that have the same country code.  In my case I am selecting United States ( or it is there by default ) I start typing 512 which is an area code in the United States and the country switches to Antigua and Barbuda. I am guessing it is because it is the first country with the country code of +1 in the list.  It probably needs to check to see if the current country selected is already the same country code before it tries to automatically make an update.  Please let me know how I can help.  But on a side note, this is a great component.

**Comment by CdTgr** [comment]
@keithchilek nice, so what you mean is to check if the user had a manual country selection and force the numbers to it or else use the auto country change?

**Comment by keithchilek** [comment]
Correct, or even for my case, the component was already selecting US, but then when I started typing it tried to select a new country even though I was already happy with the US option that was selected.  Maybe there is even a prop that lets you turn off the auto selection and just leaves it to the user to select.

**Comment by CdTgr** [comment]
@keithchilek I really liked the prop idea. I will create a new PR for this and you could do a review on it?

**Comment by keithchilek** [comment]
Yes I can do that.

**Comment by CdTgr** [comment]
@keithchilek Could you please check on the PR #35?

**Comment by CdTgr** [comment]
@keithchilek latest version is updated in npm [v1.1.7](https://www.npmjs.com/package/vue3-q-tel-input/v/1.1.7)
