### ISSUE TITLE
codepen v2 example broken on documentation

### ISSUE THREAD

**Issue by rdtome** [CdTgr/vue3-q-tel-input#44]
Hi.

It's nice to see this plugin being improved !

Please notice that ___the codepen with the V2 example is not working___ . It's the one here : https://codepen.io/CdTgr/full/PoMmeRZ

Beyond that I noticed 2 typos in the documentation : See below **"Quasar Framework"** and **"available"**.

The plugin was made over Vue3 with considering the [**Quasar Framework** v2.X](https://quasar.dev/). The plugin provides auto country detection on user inputs as well as dropdown for country which supports search by name, country code and country phone code.

Live preview for the code is **available** in [CodePen](https://codepen.io/CdTgr/full/PoMmeRZ)

**Comment by CdTgr** [comment]
@rdtome, thank you for reporting the issue. I'm happy to know that you have tried the latest version. I will check and fix the issues in the code pen.

Feel free to open a Pull Request for the changes in the documentation if you are interested ;)

**Comment by CdTgr** [comment]
@rdtome the codepen issues are fixed with [v2.0.2](https://github.com/CdTgr/vue3-q-tel-input/releases/tag/v2.0.2)

**Comment by CdTgr** [comment]
@rdtome There were also many other issues with the documentation, I have corrected and updated all of them in the release [v2.0.3](https://github.com/CdTgr/vue3-q-tel-input/releases/tag/v2.0.3)
