### ISSUE TITLE
import css doesn't work ?

### ISSUE THREAD

**Issue by Thibaut0710** [CdTgr/vue3-q-tel-input#5]
Hi! First thanks you about your package.

Seems like your import css contains a lot of code but I don't see this code into css component (Eg: countries' flags)
your css import doesn't work with ~ (import '~vue3-q-tel-input/dist/vue3-q-tel-input.esm.css')
I have forced to remove ~ on import because else quasar throws module not found error
I don't know if it's me who use badly your package or if it's real problem.

so if I am wrong, can you give me an example about how you install and use import css on your package?

**Comment by CdTgr** [comment]
@Thibaut0710 
I was using the CSS import in one of my projects within a component as
```
<script lang="ts">
import 'vue3-q-tel-input/dist/vue3-q-tel-input.esm.css'
</script>
```
Please let me know if this still doesn't work for you.

**Comment by Thibaut0710** [comment]
@CdTgr Thanks for your answer. I'm doing this too but is it normal that your component doesn't have css . An example I saw in your repo (in css folder) that you have wrote css for countries' flags but I haven't seen any flags in the list of countries. (in component's view). I'd like to know if it's normal css presence in css folder but absent in component view.

**Comment by CdTgr** [comment]
@Thibaut0710 I could still see the CSS file in the package files, are you still missing anything on your side? I just created a new project and cloned the package.
![Screen Shot 2022-02-21 at 11 38 29 PM](https://user-images.githubusercontent.com/39024474/155017102-b9100a08-21e3-4003-81a7-9115ec1adb96.png)

**Comment by Thibaut0710** [comment]
@CdTgr ,Yeah that css file is good but i was talking about css file in src folder in your github project. I see flags.css in that folder but it never use (not to my knowledge). That's why i've opened this issue. actually the component (vue-3-q-tel-input) is just an input with q-select for listing countries (it's very great for me but when i see this css folder i ask for me if it's normal or if it's not finish yet)

![css folder](https://user-images.githubusercontent.com/65714443/155026472-20e3b5ac-4a6d-43a5-b5cb-3b1d1a591f31.PNG)


(anyway thanks you for this package)

**Comment by CdTgr** [comment]
@Thibaut0710  The styles are used for the flags. You can find them [here](https://github.com/CdTgr/vue3-q-tel-input/blob/master/src/component/CountrySelection.vue#:~:text=%40import%20%27../styles/flags%27%3B) in the code.
