### ISSUE TITLE
It doesn't work (vue3)

### ISSUE THREAD

**Issue by tintin10q** [CdTgr/vue3-q-tel-input#7]
I followed the instructions:

```vue
<template>
  <div>
    hi
    <vue3-q-tel-input v-model:tel="tel" />
  </div>
</template>

<script setup lang="ts">

import {ref} from "vue";

const tel = ref('')

</script>




<script lang="ts">
import Vue3QTelInput from 'vue3-q-tel-input'
import 'vue3-q-tel-input/dist/vue3-q-tel-input.esm.css'

export default {
  name: "Phone",
  components: {Vue3QTelInput}
};
</script>
```

But I get

```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dark')```

Also I couldn't use ~ on the css import when I do that webstorm tells me `TypeError: Failed to fetch dynamically imported module`

**Comment by tintin10q** [comment]
Now I get that it just refreshes the page the whole time

**Comment by CdTgr** [comment]
@tintin10q Can you try to recreate the issue on the [latest](https://www.npmjs.com/package/vue3-q-tel-input/v/1.0.24) version?

**Comment by CdTgr** [comment]
@tintin10q The plugin doesn't use anything related to `dark` or themes. I hope you have some configurations issues on the quasar.
