### ISSUE TITLE
Red border is shown on component mount

### ISSUE THREAD

**Issue by RizaHKhan** [CdTgr/vue3-q-tel-input#8]
As soon as the component is loaded, the error border is shown. This is not desired behaviour if we are using this component in a form where other components are not eagerly validating.

**Comment by RizaHKhan** [comment]
@CdTgr Can we get trigger a NPM build? Need the latest code up so we can use it on a site.

**Comment by CdTgr** [comment]
@RizaHKhan Sorry, it was a busy month for me.
Done ✅, the new changed are pushed to npm.
